package parkingGarage;

public enum MsgTypes {
	UNDEFINED, NEWGARAGE, OPERATORLOGIN, OPERATORSUCCESS, OPERATORFAILURE, SUCCESS, NEWTICKET, LOOKUPUNPAIDTICKET,
	TICKETPAID, RECEIVED, GARAGELOGIN, SEARCHTICKET, SETRATE, GETREPORT, GETREPORTBYMONTHYEAR
}
